---
title: "Welcome"
date: 2022-05-25
---

author: AdPiscinam
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here you can see my projects

# social links
twitter_username: adpiscinam # DO NOT include the @ character, or else the build will fail!
github_username:  adpiscinam # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
---
